#!/usr/bin/bash

#SBATCH --job-name="extract_extreme_examples"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --mem=24G
#SBATCH --partition="swat_plus"
#SBATCH --time=04:00:00
#SBATCH --array=0-5
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@ou.edu
#SBATCH --output=extract_extreme_examples_%A_%a.out

host_name=`hostname`

if [[ $host_name == *"casper"* ]]; then
    TOP_EXAMPLE_DIR_NAME="/glade/scratch/ryanlage/gridrad_final/myrorss_format/tracks_with_better_polygons/reanalyzed/conus_only/tornado_occurrence/nondownsampled_2011_2015-2018/learning_examples"
    MODEL_DIR_NAME="/glade/work/ryanlage/prediction_paper_2019/gridrad_experiment/conus_only/dropout=0.500_l2=0.001000_num-dense-layers=2_data-aug=1"
    
    PYTHON_EXE_NAME="/glade/work/ryanlage/anaconda3_gpu/bin/python3.6"
    GG_DIRECTORY_NAME="/glade/work/ryanlage/gg_master"
else
    TOP_EXAMPLE_DIR_NAME="/condo/swatcommon/common/gridrad_final/myrorss_format/tracks_with_better_polygons/reanalyzed/conus_only/tornado_occurrence/nondownsampled_2011_2015-2018/learning_examples"
    MODEL_DIR_NAME="/condo/swatwork/ralager/prediction_paper_2019/gridrad_experiment/conus_only/dropout=0.500_l2=0.001000_num-dense-layers=2_data-aug=1"
    
    PYTHON_EXE_NAME="/home/ralager/anaconda3/bin/python3.6"
    GG_DIRECTORY_NAME="/condo/swatwork/ralager/gg_master"
fi

SUBSET_NAMES=("best_correct_nulls" "best_hits" "high_activation_examples" "low_activation_examples" "worst_false_alarms" "worst_misses")

this_subset_name=${SUBSET_NAMES[$SLURM_ARRAY_TASK_ID]}
echo "Array index = ${SLURM_ARRAY_TASK_ID} ... subset = ${this_subset_name}"

this_storm_metafile_name="${MODEL_DIR_NAME}/testing/extreme_examples/unique_storm_cells/${this_subset_name}.p"
this_output_file_name="${MODEL_DIR_NAME}/testing/extreme_examples/unique_storm_cells/${this_subset_name}_examples.nc"

"${PYTHON_EXE_NAME}" -u "${GG_DIRECTORY_NAME}/gewittergefahr/interpretation_paper_2019/extract_desired_examples.py" \
--input_example_dir_name="${TOP_EXAMPLE_DIR_NAME}" \
--input_storm_metafile_name="${this_storm_metafile_name}" \
--output_example_file_name="${this_output_file_name}"
