#!/usr/bin/bash

#SBATCH --job-name="make_saliency_figure"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --mem=8G
#SBATCH --partition="swat_plus"
#SBATCH --time=01:00:00
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@ou.edu
#SBATCH --output=make_saliency_figure_%A.out

host_name=`hostname`

if [[ $host_name == *"casper"* ]]; then
    MODEL_DIR_NAME="/glade/work/ryanlage/prediction_paper_2019/gridrad_experiment/conus_only/dropout=0.500_l2=0.001000_num-dense-layers=2_data-aug=1"
    
    PYTHON_EXE_NAME="/glade/work/ryanlage/anaconda3_gpu/bin/python3.6"
    GG_DIRECTORY_NAME="/glade/work/ryanlage/gg_master"
else
    MODEL_DIR_NAME="/condo/swatwork/ralager/prediction_paper_2019/gridrad_experiment/conus_only/dropout=0.500_l2=0.001000_num-dense-layers=2_data-aug=1"
    
    PYTHON_EXE_NAME="/home/ralager/anaconda3/bin/python3.6"
    GG_DIRECTORY_NAME="/condo/swatwork/ralager/gg_master"
fi

COMPOSITE_NAMES_STRING="Best_hits Worst_false_alarms Worst_misses Best_correct_nulls"

output_dir_name="${MODEL_DIR_NAME}/testing/extreme_examples/unique_storm_cells/saliency/figures_for_interpretation_paper"
saliency_files_string="${MODEL_DIR_NAME}/testing/extreme_examples/unique_storm_cells/saliency/best_hits_saliency_pmm.p ${MODEL_DIR_NAME}/testing/extreme_examples/unique_storm_cells/saliency/worst_false_alarms_saliency_pmm.p ${MODEL_DIR_NAME}/testing/extreme_examples/unique_storm_cells/saliency/worst_misses_saliency_pmm.p ${MODEL_DIR_NAME}/testing/extreme_examples/unique_storm_cells/saliency/best_correct_nulls_saliency_pmm.p"

"${PYTHON_EXE_NAME}" -u "${GG_DIRECTORY_NAME}/gewittergefahr/interpretation_paper_2019/make_saliency_figure.py" \
--input_saliency_file_names ${saliency_files_string} \
--composite_names ${COMPOSITE_NAMES_STRING} \
--max_colour_values 0.1 0.1 0.5 0.01 \
--smoothing_radius_grid_cells=1 \
--output_dir_name="${output_dir_name}"
