#!/usr/bin/bash

#SBATCH --job-name="test_gradcam_random-model"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --mem=8G
#SBATCH --partition="swat_plus"
#SBATCH --time=48:00:00
#SBATCH --array=0-5
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@ou.edu
#SBATCH --output=test_gradcam_random-model_%A_%a.out

host_name=`hostname`

if [[ $host_name == *"casper"* ]]; then
    MODEL_DIR_NAME="/glade/work/ryanlage/prediction_paper_2019/gridrad_experiment/conus_only/dropout=0.500_l2=0.001000_num-dense-layers=2_data-aug=1"
    
    PYTHON_EXE_NAME="/glade/work/ryanlage/anaconda3_gpu/bin/python3.6"
    GG_DIRECTORY_NAME="/glade/work/ryanlage/gg_master"
else
    MODEL_DIR_NAME="/condo/swatwork/ralager/prediction_paper_2019/gridrad_experiment/conus_only/dropout=0.500_l2=0.001000_num-dense-layers=2_data-aug=1"
    
    PYTHON_EXE_NAME="/home/ralager/anaconda3/bin/python3.6"
    GG_DIRECTORY_NAME="/condo/swatwork/ralager/gg_master"
fi

SUBSET_NAMES=("best_correct_nulls" "best_hits" "high_activation_examples" "low_activation_examples" "worst_false_alarms" "worst_misses")

this_subset_name=${SUBSET_NAMES[$SLURM_ARRAY_TASK_ID]}
echo "Array index = ${SLURM_ARRAY_TASK_ID} ... subset = ${this_subset_name}"

actual_gradcam_file_name="${MODEL_DIR_NAME}/testing/extreme_examples/unique_storm_cells/gradcam/${this_subset_name}_gradcam_layer3.p"
dummy_gradcam_file_name="${MODEL_DIR_NAME}/testing/extreme_examples/unique_storm_cells/gradcam/shuffled_no_downsampling/${this_subset_name}_gradcam.p"
output_file_name="${MODEL_DIR_NAME}/testing/extreme_examples/unique_storm_cells/gradcam/shuffled_no_downsampling/${this_subset_name}_gradcam_mc-test-20000.p"

"${PYTHON_EXE_NAME}" -u "${GG_DIRECTORY_NAME}/gewittergefahr/dissertation/run_mc_test_for_gradcam.py" \
--actual_gradcam_file_name="${actual_gradcam_file_name}" \
--dummy_gradcam_file_name="${dummy_gradcam_file_name}" \
--smoothing_radius_grid_cells=-1 \
--max_pmm_percentile_level=99 \
--num_iterations=20000 \
--confidence_level=0.95 \
--output_file_name="${output_file_name}"
